### ISSUE TITLE
How to grant other containers rw access to the fuse mount?

### ISSUE THREAD

**Issue by SK4G** [TorBox-App/torbox-media-center#16]
How can I grant other containers rw access to the torbox-media-center fuse mount?

Dockers containers such as Plex are unable to delete files with an error `There was a problem deleting this item`

The host and torbox-media-center container give the following error when trying to write to the mount location
```
# touch /mnt/torbox/movies/testfile
touch: cannot touch '/mnt/torbox/movies/testfile': Function not implemented
```

I am using the compose from [docker.md](https://github.com/TorBox-App/torbox-media-center/blob/main/docker.md#standard-docker-run-command-fuse)

```
name: torbox-media-center
services:
  torbox-media-center:
    stdin_open: true
    tty: true
    container_name: torbox-media-center
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    volumes:
      - /mnt/torbox:/torbox:rshared
    environment:
      - TORBOX_API_KEY=xxxxxxxxxxxx
      - MOUNT_METHOD=fuse
      - MOUNT_PATH=/torbox
      # also tried adding the below options
      - PUID=1000
      - PGID=1000
      - MOUNT_OPTIONS=--allow-other --uid 1000 --gid 1000 --umask 002

    image: ghcr.io/torbox-app/torbox-media-center:main
```
