### ISSUE TITLE
Docker-compose stuck pulling

### ISSUE THREAD

**Issue by SimoMay** [TorBox-App/torbox-media-center#18]
Docker-compose stuck pulling

`torbox-media-center [⣿⣿⣀⣿⣿⣿⣿⣿⣿⣿⣿] 4.105MB / 16.41MB Pulling   995.2s`

My config:
```
  torbox-media-center:
    container_name: torbox-media-center
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ~/xxx/xxx/torbox:/torbox
    environment:
      - TORBOX_API_KEY=xxx
      - MOUNT_METHOD=fuse
      - MOUNT_PATH=/torbox
    image: anonymoussystems/torbox-media-center:latest
```
